// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using iStore.Models;

namespace iStore.Migrations.ProductDb
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20210929064637_AddedCartAndWishlist")]
    partial class AddedCartAndWishlist
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("iStore.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CustomerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Zipcode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("carts");
                });

            modelBuilder.Entity("iStore.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "It has a 8GB Ram/512GB ROM and a processor of A15 bionic chip with a display of 6.7 inches",
                            Name = "iPhone13ProMax",
                            Price = 139900,
                            Rating = 9.8m
                        },
                        new
                        {
                            Id = 2,
                            Description = "It has a 8GB Ram/256GB ROM and a processor of A15 bionic chip with a display of 6.1 inches",
                            Name = "iPhone13Pro",
                            Price = 119900,
                            Rating = 9.6m
                        },
                        new
                        {
                            Id = 3,
                            Description = "It has a 8GB Ram/256GB ROM and a processor of A15 bionic chip with a display of 6.1 inches",
                            Name = "iPhone13",
                            Price = 69900,
                            Rating = 9.4m
                        },
                        new
                        {
                            Id = 4,
                            Description = "It has a 4GB Ram/128GB ROM and a processor of A13 bionic chip with a display of 5.4 inches",
                            Name = "iPhone13Mini",
                            Price = 65900,
                            Rating = 9.2m
                        },
                        new
                        {
                            Id = 5,
                            Description = "It has a 8GB Ram/512GB ROM and a processor of A14 bionic chip with a display of 6.7 inches",
                            Name = "iPhone12ProMax",
                            Price = 100900,
                            Rating = 9.5m
                        },
                        new
                        {
                            Id = 6,
                            Description = "It has a 8GB Ram/256GB ROM and a processor of A14 bionic chip with a display of 6.1 inches",
                            Name = "iPhone12Pro",
                            Price = 90900,
                            Rating = 9.3m
                        },
                        new
                        {
                            Id = 7,
                            Description = "It has a 6GB Ram/128GB ROM and a processor of A14 bionic chip with a display of 5.4 inches",
                            Name = "iPhone12",
                            Price = 59900,
                            Rating = 9.1m
                        },
                        new
                        {
                            Id = 8,
                            Description = "It has a 6GB Ram/64GB ROM and a processor of A14 bionic chip with a display of 4.7 inches",
                            Name = "iPhone12Mini",
                            Price = 56900,
                            Rating = 8.5m
                        },
                        new
                        {
                            Id = 9,
                            Description = "It has a 4GB Ram/64GB ROM and a processor of A14 bionic chip with a display of 6.7 inches",
                            Name = "iPhoneSE",
                            Price = 39900,
                            Rating = 8.3m
                        },
                        new
                        {
                            Id = 10,
                            Description = "It has a 8GB Ram/512GB ROM and a processor of A13 bionic chip with a display of 6.5 inches",
                            Name = "iPhone11ProMax",
                            Price = 65900,
                            Rating = 9.1m
                        },
                        new
                        {
                            Id = 11,
                            Description = "It has a 8GB Ram/256GB ROM and a processor of A12 bionic chip with a display of 5.8 inches",
                            Name = "iPhone11Pro",
                            Price = 55900,
                            Rating = 8.9m
                        },
                        new
                        {
                            Id = 12,
                            Description = "It has a 6GB Ram/128GB ROM and a processor of A13 bionic chip with a display of 6.1 inches",
                            Name = "iPhone11",
                            Price = 49900,
                            Rating = 8.5m
                        },
                        new
                        {
                            Id = 13,
                            Description = "It has a 6GB Ram/256GB ROM and a processor of A13 bionic chip with a display of 5.8 inches",
                            Name = "iPhoneX",
                            Price = 52900,
                            Rating = 8.5m
                        },
                        new
                        {
                            Id = 14,
                            Description = "It has a 8GB Ram/512GB ROM and a processor of A12 bionic chip with a display of 6.5 inches",
                            Name = "iPhoneXSMAX",
                            Price = 55900,
                            Rating = 8.8m
                        },
                        new
                        {
                            Id = 15,
                            Description = "It has a 6GB Ram/128GB ROM and a processor of A12 bionic chip with a display of 5.8 inches",
                            Name = "iPhoneXS",
                            Price = 49900,
                            Rating = 8.3m
                        },
                        new
                        {
                            Id = 16,
                            Description = "It has a 8GB Ram/64GB ROM and a processor of A12 bionic chip with a display of 6.1 inches",
                            Name = "iPhoneXR",
                            Price = 45900,
                            Rating = 8.1m
                        },
                        new
                        {
                            Id = 17,
                            Description = "It has a 6GB Ram/128GB ROM and a processor of A11 bionic chip with a display of 5.5 inches",
                            Name = "iPhone8Plus",
                            Price = 40900,
                            Rating = 7.9m
                        },
                        new
                        {
                            Id = 18,
                            Description = "It has a 4GB Ram/64GB ROM and a processor of A11 bionic chip with a display of 4.7 inches",
                            Name = "iPhone8",
                            Price = 38900,
                            Rating = 7.5m
                        },
                        new
                        {
                            Id = 19,
                            Description = "It has a 4GB Ram/128GB ROM and a processor of A10 bionic chip with a display of 5.4 inches",
                            Name = "iPhone7Plus",
                            Price = 35900,
                            Rating = 7.6m
                        },
                        new
                        {
                            Id = 20,
                            Description = "It has a 4GB Ram/64GB ROM and a processor of A10 bionic chip with a display of 4.7 inches",
                            Name = "iPhone7",
                            Price = 33900,
                            Rating = 7.2m
                        },
                        new
                        {
                            Id = 21,
                            Description = "It has a 8GB Ram/128GB ROM and a processor of M1 chip with a display of 11 inches",
                            Name = "iPadPro",
                            Price = 71900,
                            Rating = 9.5m
                        },
                        new
                        {
                            Id = 22,
                            Description = "It has a 6GB Ram/64GB ROM and a processor of A14 bionic chip with a display of 10.9 inches",
                            Name = "iPadAir",
                            Price = 54900,
                            Rating = 9.1m
                        },
                        new
                        {
                            Id = 23,
                            Description = "It has a 6GB Ram/128GB ROM and a processor of A13 bionic chip with a display of 10.2 inches",
                            Name = "iPad",
                            Price = 46900,
                            Rating = 8.7m
                        },
                        new
                        {
                            Id = 24,
                            Description = "It has a 4 GB Ram,64 GB of ROM and a processor of A15 bionic chip with a display of 8.3 inches",
                            Name = "iPadMini",
                            Price = 35900,
                            Rating = 8.5m
                        });
                });

            modelBuilder.Entity("iStore.Models.Vendor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DeliveryCharge")
                        .HasColumnType("int");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VendorName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("vendors");
                });

            modelBuilder.Entity("iStore.Models.VendorStock", b =>
                {
                    b.Property<DateTime>("ExpectedStockReplinshmentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductID")
                        .HasColumnType("int");

                    b.Property<int>("StockInHand")
                        .HasColumnType("int");

                    b.Property<int>("VendorID")
                        .HasColumnType("int");

                    b.ToTable("vendorStocks");
                });

            modelBuilder.Entity("iStore.Models.VendorWishlist", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAddedToWishlist")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Qunatity")
                        .HasColumnType("int");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.ToTable("vendorWishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
